name: tug


packages:
  - packages/*

scripts:

  get:
    run: |
      flutter clean
      flutter pub get

  freeze:
    run: |
      flutter pub run build_runner build --delete-conflicting-outputs
